export const education = [
  {
    id: 1,
    level: "Higher Education",
    institution: "BAHRIA UNIVERSITY ISLAMABAD CAMPUS",
    degree: "Bachelor of Computer Engineering",
    year: 2024,
    percentage: "3.00 CGPA",
    subjects: [
      "Data Structures and Algorithms, ",
      "Database Management Systems, ",
      "Operating Systems, ",
      "Computer Networks, ",
      "Computer Programming",
    ],
  },
  {
    id: 2,
    level: "Intermediate",
    institution: "SSAT DEGREE COLLEGE",
    degree: "Pre-Engineering",
    year: 2019,
    percentage: "70%",
    subjects: ["Physics, ", "Chemistry, ", "Mathematics, ", "English"],
  },
  {
    id: 3,
    level: "Matriculation",
    institution: "SYYEDI SCHOOLING SYSTEM",
    degree: "Science Group",
    year: 2017,
    percentage: "75%",
    subjects: ["Math, ", "Science, ", "English, ", "Pakistan Studies"],
  },
];
